### ISSUE TITLE
Meta: stable plugins

### ISSUE THREAD

**Issue by aturon** [aturon/moco-rust-planning#29]
- [X] Blog: plugin design: https://github.com/aturon/moco-rust-planning/issues/6
- [ ] RFC for name resolution: https://github.com/aturon/moco-rust-planning/issues/23
- [ ] RFC for incorporating macros into module system: https://github.com/aturon/moco-rust-planning/issues/24
- [ ] RFC for core syntax extensions: https://github.com/aturon/moco-rust-planning/issues/25
- [ ] RFC for libmacro: https://github.com/aturon/moco-rust-planning/issues/26
- [ ] RFC for macro-by-example 2.0: https://github.com/aturon/moco-rust-planning/issues/27
- [ ] Code: sets-of-scopes hygiene: https://github.com/aturon/moco-rust-planning/issues/28
